---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: "false"   # temporarily make Flux ignore a manifest if set to true
    fluxcd.io/automated: "false"  # automated deployment of new container images
spec:
  releaseName: metrics-server
  helmVersion: v3
  chart:
    # Helm Charts: https://github.com/bitnami/charts/tree/master/bitnami/metrics-server
    repository: https://charts.bitnami.com/bitnami
    name: metrics-server
    version: 5.3.3
  values:
    image:
      registry: docker.io
      repository: bitnami/metrics-server
      tag: 0.4.1
      pullPolicy: IfNotPresent
    rbac:
      create: true
    serviceAccount:
      create: true
    apiService:
      ## Create the v1beta1.metrics.k8s.io API service
      ## This should not be necessary in k8s version >= 1.8
      create: true
    hostNetwork: true  # for overlay networking
    extraArgs:
      kubelet-preferred-address-types: InternalIP
      logtostderr: true
      # v: 2 # log verbosity