---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: sandbox
  name: ingress-sandbox-ssl-redirect
  annotations:
    kubernetes.io/ingress.class: merge
    merge.ingress.kubernetes.io/config: merged-ingress-sandbox
    merge.ingress.kubernetes.io/priority: "9999"
spec:
  rules:
    - http:
        paths:
         - path: /*
           backend:
             serviceName: ssl-redirect
             servicePort: use-annotation