---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube2iam
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: false   # temporarily make Flux ignore a manifest if set to true
    fluxcd.io/automated: true  # automated deployment of new container images
    filter.fluxcd.io/chart-image: semver:0.10.8
spec:
  releaseName: kube2iam
  chart:
    # Helm Charts: https://github.com/kubernetes/charts/tree/master/stable/kube2iam
    repository: https://kubernetes-charts.storage.googleapis.com
    name: kube2iam
    version: 2.1.0
  valueFileSecrets:
    - name: kube2iam
  values:
    image:
      repository: jtblin/kube2iam
      tag: 0.10.8
      pullPolicy: IfNotPresent
    host:
      iptables: true
      interface: eni+
    rbac:
      create: true
    tolerations:
      - effect: NoSchedule
        operator: Exists

#    Injected by Flux - using secrets
#    extraArgs:
#      base-role-arn: arn:aws:iam::${account_id}:role/  # Replace the account number

