---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: alb-controller
  namespace: admin
  annotations:
    fluxcd.io/ignore: "false"   # temporarily make Flux ignore a manifest if set to true
    fluxcd.io/automated: "false"  # automated deployment of new container images
spec:
  releaseName: alb-controller
  helmVersion: v3
  chart:
    # Helm Charts: https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller
    repository: https://aws.github.io/eks-charts
    name: aws-load-balancer-controller
    version: 1.1.0
  valueFileSecrets:
    - name: alb-controller
  values:
    image:
      repository: amazon/aws-load-balancer-controller
      tag: v2.1.0
      pullPolicy: IfNotPresent
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nodetype
                  operator: In
                  values:
                    - ondemand
                - key: nodegroup
                  operator: In
                  values:
                    - eks

#    Injected by Flux - using secrets
#    clusterName: ${cluster_name}
#    rbac:
#      create: true
#    serviceAccount:
#      create: true
#      annotations:
#        eks.amazonaws.com/role-arn: "${service_account_arn}"