# WARNING: This setup is using deprecated helm chart: https://github.com/helm/charts/tree/master/incubator/fluentd-cloudwatch
#   See aws recommendation: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs.html
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluentd-cloudwatch
  namespace: admin
  annotations:
    fluxcd.io/ignore: "false"   # temporarily make Flux ignore a manifest if set to true
    fluxcd.io/automated: "false"  # automated deployment of new container images
spec:
  releaseName: fluentd-cloudwatch
  chart:
    # Helm Charts: https://github.com/helm/charts/tree/master/incubator/fluentd-cloudwatch
    repository: https://kubernetes-charts-incubator.storage.googleapis.com
    name: fluentd-cloudwatch
    version: 0.13.2
  valueFileSecrets:
    - name: fluentd-cloudwatch
  values:
    image:
      repository: fluent/fluentd-kubernetes-daemonset
      tag: v1.14.1-debian-cloudwatch-1.0
      pullPolicy: IfNotPresent
    rbac:
      create: true
    extraVars:
      - "{ name: FLUENT_UID, value: '0' }"
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nodetype
                  operator: In
                  values:
                    - ondemand
                - key: nodegroup
                  operator: In
                  values:
                    - eks

#    Injected by Flux - using secrets
#    rbac:
#      serviceAccount:
#        annotations:
#          eks.amazonaws.com/role-arn: "${service_account_arn}"
#    logGroupName: ${cluster_name}-logs
#    awsRegion: ${region}