---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluentd-cloudwatch
  namespace: admin
  annotations:
    fluxcd.io/ignore: false   # temporarily make Flux ignore a manifest if set to true
    fluxcd.io/automated: true  # automated deployment of new container images
    filter.fluxcd.io/chart-image: semver:v1.7.3-debian-cloudwatch-1.0
spec:
  releaseName: fluentd-cloudwatch
  chart:
    # Helm Charts: https://github.com/helm/charts/tree/master/incubator/fluentd-cloudwatch
    repository: https://kubernetes-charts-incubator.storage.googleapis.com
    name: fluentd-cloudwatch
    version: 0.12.1
  valueFileSecrets:
    - name: fluentd-cloudwatch
  values:
    image:
      repository: fluent/fluentd-kubernetes-daemonset
      tag: v1.7.3-debian-cloudwatch-1.0
      pullPolicy: IfNotPresent
    rbac:
      create: true
    extraVars:
      - "{ name: FLUENT_UID, value: '0' }"
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi

#    Injected by Flux - using secrets
#    awsRole: ${cluster_name}-fluentd
#    logGroupName: ${cluster_name}-logs
#    awsRegion: ${region}
