---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kubewatch
  namespace: admin
  annotations:
    fluxcd.io/ignore: "false"   # temporarily make Flux ignore a manifest if set to true
    fluxcd.io/automated: "false"  # automated deployment of new container images
spec:
  releaseName: kubewatch
  helmVersion: v3
  chart:
    # Helm Charts: https://github.com/helm/charts/tree/master/stable/kubewatch
    repository: https://charts.bitnami.com/bitnami
    name: kubewatch
    version: 3.0.0
  values:
    image:
      repository: bitnami/kubewatch
      tag: 0.1.0
      pullPolicy: IfNotPresent
    slack:
      enabled: false
      channel: ""
      token: ""
    hipchat:
      enabled: false
    mattermost:
      enabled: false
    flock:
      enabled: false
    webhook:
      enabled: false
    resourcesToWatch:
      daemonset: true
      deployment: true
      job: true
      persistentvolume: true
      pod: true
      replicationcontroller: true
      replicaset: true
      services: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nodetype
                  operator: In
                  values:
                    - ondemand
                - key: nodegroup
                  operator: In
                  values:
                    - eks
