---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: admin
  annotations:
    fluxcd.io/ignore: false   # temporarily make Flux ignore a manifest if set to true
    fluxcd.io/automated: true  # automated deployment of new container images
    filter.fluxcd.io/chart-image: semver:0.5.17
spec:
  releaseName: external-dns
  chart:
    # Helm Charts: https://github.com/helm/charts/tree/master/stable/external-dns
    repository: https://kubernetes-charts.storage.googleapis.com
    name: external-dns
    version: 2.13.2
  valueFileSecrets:
    - name: external-dns
  values:
    image:
      repository: bitnami/external-dns
      tag: 0.5.17
      pullPolicy: IfNotPresent
    rbac:
      create: true
    sources:
      - service
      - ingress

#    Injected by Flux - using secrets
#    podAnnotations:
#      iam.amazonaws.com/role: ${cluster_name}-external-dns
