---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluentd-cloudwatch
  namespace: admin
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:v1.7.3-debian-cloudwatch-1.0
spec:
  releaseName: fluentd-cloudwatch
  chart:
    # Helm Charts: https://github.com/helm/charts/tree/master/incubator/fluentd-cloudwatch
    repository: https://kubernetes-charts-incubator.storage.googleapis.com
    name: fluentd-cloudwatch
    version: 0.12.1
  values:
    image:
      repository: fluent/fluentd-kubernetes-daemonset
      tag: v1.7.3-debian-cloudwatch-1.0
      pullPolicy: IfNotPresent
    rbac:
      create: true
    extraVars:
      - "{ name: FLUENT_UID, value: '0' }"
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    awsRole: odc-test-stage-odc-eks-fluentd
    logGroupName: odc-test-stage-odc-eks-datakube
    awsRegion: ap-southeast-2
