---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kubewatch
  namespace: admin
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:v0.0.4
spec:
  releaseName: kubewatch
  chart:
    # Helm Charts: https://github.com/helm/charts/tree/master/stable/kubewatch
    repository: https://kubernetes-charts.storage.googleapis.com
    name: kubewatch
    version: 1.0.1
  values:
    image:
      repository: bitnami/kubewatch
      tag: 0.0.4
      pullPolicy: IfNotPresent
    slack:
      enabled: false
      channel: ""
      token: ""
    hipchat:
      enabled: false
    mattermost:
      enabled: false
    flock:
      enabled: false
    webhook:
      enabled: false
    resourcesToWatch:
      daemonset: true
      deployment: true
      job: true
      persistentvolume: true
      pod: true
      replicationcontroller: true
      replicaset: true
      services: true
