---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ows
  namespace: web
  annotations:
    fluxcd.io/ignore: false   # temporarily make Flux ignore a manifest if set to true
    fluxcd.io/automated: true  # automated deployment of new container images
    fluxcd.io/tag.global: glob:*
    fluxcd.io/tag.wmsConfig: glob:*
spec:
  releaseName: ows
  chart:
    # Helm Charts: https://github.com/opendatacube/datacube-charts/tree/master/stable/datacube
    repository: https://opendatacube.github.io/datacube-charts/charts/
    name: datacube
    version: 0.17.10
  valueFileSecrets:
    - name: ows
  values:
    image:
      # Docker Hub: https://hub.docker.com/r/opendatacube/wms
      # Source Repository: https://github.com/opendatacube/datacube-ows
      registry: docker.io
      tag: "0.13.2"
      repository: opendatacube/ows
      pullPolicy: IfNotPresent
#    Injected by Flux - using secrets
#    database:
#      database: ${db_name}
#      host: ${db_hostname}
#      existingSecret: ${db_secret}
    clusterInfo:
      envName: dev
    minReplicas: 20
    maxReplicas: 50
    wms:
#      Injected by Flux - using secrets
#      annotations:
#        iam.amazonaws.com/role: ${role_name}
      dockerArgs:
        - "gunicorn"
        - "-b"
        - "0.0.0.0:8000"
        - "-w"
        - "3"
        - "--threads=3"
        - "-k"
        - "gevent"
        - "--timeout"
        - "121"
        - "--graceful-timeout"
        - "121"
        - "--keep-alive"
        - "5"
        - "--pid"
        - "gunicorn.pid"
        - "--backlog"
        - "64"
        - "--log-level"
        - "info"
        - "--worker-tmp-dir"
        - "/dev/shm"
        - "datacube_ows.wsgi"
      enabled: true
      externalPort: 80
      internalPort: 8000
      targetCpu: 250
      resources:
        requests:
          cpu: "250m"
          memory: 4096Mi
        limits:
          cpu: 4
          memory: 8192Mi
      maxSurge: 25%
      maxUnavailable: 10%
      readinessProbe:
        exec:
          command:
            - "/bin/sh"
            - "-c"
            - "curl --silent 'http://localhost:8000/ping'"
        periodSeconds: 30
        initialDelaySeconds: 10
        timeoutSeconds: 5
      livenessProbe:
        exec:
          command:
            - "/bin/sh"
            - "-c"
            - "curl --silent 'http://localhost:8000/ping'"
        periodSeconds: 30
        initialDelaySeconds: 10
        timeoutSeconds: 5
#      Injected by Flux - using secrets
#      awsCredentialsSecret: ows-user-creds
      additionalEnvironmentVars:
        GDAL_DISABLE_READDIR_ON_OPEN: "EMPTY_DIR"
        CPL_VSIL_CURL_ALLOWED_EXTENSIONS: ".tif"
        GDAL_HTTP_MAX_RETRY: 10
        GDAL_HTTP_RETRY_DELAY: 1
        DATACUBE_OWS_CFG: config.ows_cfg.ows_cfg
    wmsConfig:
      # if using docker or configmap
      path: /opt/config
      filename: ows_cfg.py
      subPath: config
      # configMap: cfg_map_name
      # url: cfg_url
      image:
        # Docker Hub: https://hub.docker.com/r/geoscienceaustralia/dea-datakube-config
        # Source Repository: https://github.com/GeoscienceAustralia/dea-config
        registry: docker.io
        repository: geoscienceaustralia/dea-datakube-config
        tag: "1.4.10-unstable.5.g266d1d0"
        pullPolicy: IfNotPresent
        src: /opt/dea-config/dev/services/wms/ows/ows_cfg.py
    ingress:
      enabled: true
#      Injected by Flux - using secrets
#      hosts:
#      - ows.${domain_name}
      annotations:
        kubernetes.io/ingress.class: merge
        merge.ingress.kubernetes.io/config: merged-ingress
        merge.ingress.kubernetes.io/priority: "0"
    service:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: "/ping"
        alb.ingress.kubernetes.io/healthcheck-interval-seconds: "60"
        alb.ingress.kubernetes.io/target-group-attributes: "load_balancing.algorithm.type=least_outstanding_requests"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nodetype
                  operator: NotIn
                  values:
                    - spot